### ISSUE TITLE
0.2 Roadmap

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#202]
I've added all that I feel are important but feel free to add (or remove) more

**Priorities**

- [x] Code refactor (https://github.com/scikit-optimize/scikit-optimize/issues/158)
- [x] Benchmarks - (https://github.com/scikit-optimize/scikit-optimize/issues/180)
- [ ] Docs via the example notebooks - (https://github.com/scikit-optimize/scikit-optimize/issues/129)

(All the remaining are nice to have for now)

**Gaussian Processes**:

 - [x] Normalize transformed space to 0, 1 (https://github.com/scikit-optimize/scikit-optimize/pull/161)
 - [ ] Beta Warping (Nice to have)
 - [ ] Full support for categorical parameters (https://github.com/scikit-optimize/scikit-optimize/pull/62)
 - [ ] Better default kernels (https://github.com/scikit-optimize/scikit-optimize/issues/192)

**RF based**:

 - [ ] Pseudo-sampling techniques (https://github.com/scikit-optimize/scikit-optimize/issues/193)

**API**: 

- [x] Loading and saving instance of OptimizeResult objects (https://github.com/scikit-optimize/scikit-optimize/issues/190 PR in #245)
- [ ] Conditional search spaces - (https://github.com/scikit-optimize/scikit-optimize/issues/108/)

**Comment by betatim** [comment]
I am keen to see #108 happen (API) and a decision on what kind of narrative docs we will have (or not).

**Comment by MechCoder** [comment]
Updated after our talk on hangouts. Do we have a time deadline in mind?

**Comment by betatim** [comment]
How about ~2months? Keep things rolling, not try and cook a monster release, and have something "big" in each release.

**Comment by stonebig** [comment]
Don't you want to do an intermediate release this week, following Scikit-learn-0.18.0 ?

**Comment by betatim** [comment]
I don't think we need to do that. You should be able to use the new version of scikit-learn and scikit-optimize-0.1.

**Comment by stonebig** [comment]
you may so change the target date of milestone 0.2

**Comment by MechCoder** [comment]
Closing this in favour of the new project interface (https://github.com/scikit-optimize/scikit-optimize/projects/1). It makes it easier to track things.

**Comment by betatim** [comment]
Is there a way to discuss what is/should be on the roadmap for a project with the new project interface? I had a quick look but couldn't find it :-/ I think we should maintain a way to discuss the "why" not just track "what" :)
