### ISSUE TITLE
Release checklist v0.3

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#312]
I think we can release after https://github.com/scikit-optimize/scikit-optimize/pull/306 and https://github.com/scikit-optimize/scikit-optimize/pull/311

Apart from https://github.com/scikit-optimize/scikit-optimize/issues/260 we should do the following.

Codebase related:

- [ ] Check if all the changes (especially bug fixes and API changes) are in the Changelog
- [ ] Check if all parameters are documented correctly. (for eg, default values etc)
- [x] Check if the examples work as expected.
- [ ] Run the benchmarks and check if they do as promised (good or bad)
- [x] Check if the documentation renders as expected.

Others:

- [ ] working [PyPi test site](https://testpypi.python.org/pypi/skopt/0.0) account?
- [ ] set `__version__` and update `setup.py`
- [ ] PyPi test site release (mostly follows https://packaging.python.org/distributing/#packaging-your-project)
  - `python setup.py sdist`
  - `python setup.py bdist_wheel --universal` (as long as we are pure python we can provide universal wheels)
  - check that `dist/` doesn't contain any rubbish/old releases
  - `twine register -r pypitest dist/scikit_optimize-0.2-py2.py3-none-any.whl`
  - `twine upload -r pypitest dist/*`
- [ ] [release on github](https://github.com/scikit-optimize/scikit-optimize/releases)
- [ ] PyPi (mostly follows https://packaging.python.org/distributing/#packaging-your-project)
  - `python setup.py sdist`
  - `python setup.py bdist_wheel --universal` (as long as we are pure python we can provide universal wheels)
  - `twine register` doesn't seem to be required for the real pypi so this command doesn't complete but doesn't seem to cause a problem
  - check that `dist/` doesn't contain any rubbish/old releases
  - `twine upload dist/*`
Anything else?

**Comment by glouppe** [comment]
#306 and #311 are now merged. Would be happy with a 0.3 release :)

**Comment by MechCoder** [comment]
KK @betatim please do the honours.

**Comment by betatim** [comment]
Ok, just got back from skiing ⛰ ⛷  will get on this tomorrow (Sunday) afternoon. We should figure out why #314 has failing tests before the release.

**Comment by betatim** [comment]
> Check if all parameters are documented correctly. (for eg, default values etc)

is there a tool we can use? I started looking and quickly realised that we are extremely inconsistent with our uses of ` ``variable`` ` vs `` `variable` ``, "default: False" vs "(default: False)" etc. I think if we really want to get a consistent style we should have some kind of tool that helps us spot deviations as code is being committed.

**Comment by betatim** [comment]
I'd like to try automating the deployment to pypi: #319 and will fix a few doc string violations on the way. If you have a spare moment to go through some that would be good :smile

**Comment by glouppe** [comment]
Hey. Do you need my help for anything specific regarding the preparation of 0.4?

**Comment by betatim** [comment]
You mean v0.3 no?

I think we shouldn't wait for finding all the inconsistent doc strings before releasing 0.3. What would be good is if we could write down somewhere what they should look like (or just link to a good example in the code base) so that in the future we can become more consistent.

**Comment by betatim** [comment]
https://github.com/scikit-optimize/scikit-optimize/releases/tag/v0.3

let's see if travis does its thing and uploads to pypi etc

**Comment by betatim** [comment]
Looks like a great success. https://pypi.python.org/pypi/scikit-optimize

:champagne: all around for everyone who helped!

next stop v0.4!

**Comment by glouppe** [comment]
Yay! :beers:
